### PR TITLE
Yarn && Styling

### LINKED ISSUE #11: Uniform styling across project

### PR DESCRIPTION
**Pull request by walterimaican**
- Moved to yarn workspaces
- Added linting and styling auto-enabled on commits
- Applied `eslint` and `prettier` to codebase

**Recommendation**
After merging this PR and pulling changes, delete existing `node_modules` folders and `package-lock.json` files and follow `README.md` steps for installation

### CODE REVIEW

**Comment by walterimaican** [comment]
CI/CD may have to be updated due to use of `yarn` and `yarn.lock` at the expense of deleting `package-lock.json`

**Comment by jfabellera** [comment]
I'm getting warnings for mongoose with this PR:

```
[backend-auth   ] (node:17704) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
[backend-auth   ] (Use `node --trace-warnings ...` to show where the warning was created)
[backend-express] (node:13672) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
[backend-express] (Use `node --trace-warnings ...` to show where the warning was created)
[backend-auth   ] MongoDB connection established
[backend-auth   ] (node:17704) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
[backend-express] MongoDB connection established
[backend-express] (node:13672) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
```

**Comment by jfabellera** [comment]
Never mind, these were introduced with Mongoose 3.6.4 and can be ignored according to [here](https://developer.mongodb.com/community/forums/t/node-44612-deprecationwarning-listening-to-events-on-the-db-class-has-been-deprecated-and-will-be-removed-in-the-next-major-version/15849/2) and [here](https://developer.mongodb.com/community/forums/t/warning-accessing-non-existent-property-mongoerror-of-module-exports-inside-circular-dependency/15411/4)

**Review by jfabellera — APPROVED** [review]
Nice work, gonna make developing easier!

**Pull request merged**
