### PR TITLE
migrate to mongoose

### PR DESCRIPTION
**Pull request by jfabellera**
migrates mongodb management from monk to mongoose

### CODE REVIEW

**Review by carlaequihua — COMMENTED** [review]
Let’s get some feedback on our preferred linting standard. ‘>”

**Comment by jfabellera** [comment]
@boogerztasty '>"?

**Comment by walterimaican** [comment]
Prefer single quotes (') over double quotes ("). You can also use ESLint and Prettier in combination with each other to automate linting and styling across your JS, HTML, CSS, JSON, etc.

**Comment by jfabellera** [comment]
Yeah I was just using the default settings in Prettier.

**Comment by jfabellera** [comment]
We can have a separate PR for styling

**Pull request merged**
